version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sportify
      POSTGRES_PASSWORD: "QhgEpio4WxiJvTxTPoYeSfuoNCeOJ285"
    volumes:
      - sportify_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "h4b-xHZ2csKj2cqCupEUiIaRGEO494hO"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  sportify_data:
